// This file was auto-generated by ML.NET Model Builder. 
namespace MlDemoML.Model
{
    using System;
    using Microsoft.ML;

    public class ConsumeModel
    {
        private static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictionEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(CreatePredictionEngine);

        // For more info on consuming ML.NET models, visit https://aka.ms/mlnet-consume
        // Method for consuming model in your app
        public static ModelOutput Predict(ModelInput input)
        {
            var result = PredictionEngine.Value.Predict(input);
            return result;
        }

        public static PredictionEngine<ModelInput, ModelOutput> CreatePredictionEngine()
        {
            // Create new MLContext
            var mlContext = new MLContext();

            // Load model & create prediction engine
            const string modelPath = @".\MLModel.zip";
            var mlModel = mlContext.Model.Load(modelPath, out var modelInputSchema);
            var predictionEngine = mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);

            return predictionEngine;
        }
    }
}
